#!/usr/bin/env bash
# Copy talk-safe figures into presentation_figures/ (repo root) for easy grab + push.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/presentation_figures"
rm -rf "$DEST"
mkdir -p "$DEST"/{agents,open_pipeline,master_ladders,mechanistic,w3_w4_w7,extras}

copy() { # src dest_subdir [rename]
  local src="$1" sub="$2" name="${3:-$(basename "$1")}"
  [[ -f "$src" ]] || { echo "skip missing: $src"; return 0; }
  cp -f "$src" "$DEST/$sub/$name"
  echo "  $sub/$name"
}

echo "Packing -> $DEST"

echo "== agents (closed v3 + scale_all) =="
for f in \
  agent_scale.png agent_scale_all.png \
  agent_contrast_forest.png agent_profiles.png \
  agent_prompt_invariance.png agent_scale_vs_contrast.png \
  agent_contrast_vs_scale.png agent_weights.png agent_pairwise.png \
  agent_contrast_forest_human_only.png
do
  copy "$ROOT/outputs/agents/figures/$f" agents
done

echo "== open pipeline (outputs/figures) =="
for f in contrast_forest.png profiles.png prompt_invariance.png \
         size_vs_contrast.png weights_scatter.png pairwise_heatmap.png
do
  copy "$ROOT/outputs/figures/$f" open_pipeline "open_$f"
done

echo "== master ladders + figures_final (talk-safe; no STALE) =="
for f in \
  master_developmental_ladder_digitized_openonly.png \
  master_developmental_ladder_punish_openonly.png \
  master_developmental_ladder_text_reported_openonly.png \
  checkpoint_dissection.png \
  gap_over_surface_span_matched.png \
  layerwise_curves.png \
  rsa_similarity_heatmap.png \
  rsa_convergence_scatter.png \
  item_level_dissociation.png \
  interaction_forest.png \
  tom_vs_contrast.png \
  w3_steering_dose_OLMo.png w3_steering_dose_Qwen.png \
  w3_layersweep_OLMo.png w3_layersweep_Qwen.png \
  w3_manipulation_OLMo.png w3_manipulation_Qwen.png \
  w3_prose_rating.png \
  w4_curriculum.png \
  w7_bruneau_selectivity.png \
  agent_contrast_forest_v3_nopro.png
do
  # Prefer figures_final, else root outputs, else updated_figures
  if [[ -f "$ROOT/outputs/figures_final/$f" ]]; then
    copy "$ROOT/outputs/figures_final/$f" master_ladders
  elif [[ -f "$ROOT/outputs/$f" ]]; then
    copy "$ROOT/outputs/$f" master_ladders
  elif [[ -f "$ROOT/outputs/updated_figures/$f" ]]; then
    copy "$ROOT/outputs/updated_figures/$f" master_ladders
  else
    echo "skip missing: $f"
  fi
done

# Route W3/W4 into their own subfolder (also keep copies under master_ladders names above)
for f in w3_*.png w4_*.png w7_*.png; do
  for src in "$DEST"/master_ladders/$f; do
    [[ -f "$src" ]] && cp -f "$src" "$DEST/w3_w4_w7/$(basename "$src")"
  done
done 2>/dev/null || true

echo "== mechanistic extras from updated_figures =="
for f in \
  human_only_developmental_ladder.png \
  mixed_effects_interaction.png \
  gap_over_surface_dissociation.png \
  gap_over_surface_dissociation_span_matched.png \
  cushman_digitized_overlay.png \
  model_similarity_heatmap_rsa_spearman.png \
  model_similarity_heatmap_cka_linear.png \
  rep_vs_behavior.png
do
  copy "$ROOT/outputs/updated_figures/$f" mechanistic
done

echo "== mentor packet uniques =="
for f in \
  w3_steering_OLMo-2-1124-7B-Instruct.png \
  w3_steering_Qwen2.5-7B-Instruct.png
do
  copy "$ROOT/outputs/mentor_packet_figures/$f" extras
done

# Flat convenience copies of the headline slides
mkdir -p "$DEST/_headline"
for f in \
  agents/agent_contrast_forest.png \
  agents/agent_scale_all.png \
  agents/agent_scale.png \
  agents/agent_profiles.png \
  master_ladders/master_developmental_ladder_digitized_openonly.png \
  master_ladders/w4_curriculum.png \
  master_ladders/checkpoint_dissection.png \
  master_ladders/tom_vs_contrast.png
do
  [[ -f "$DEST/$f" ]] && cp -f "$DEST/$f" "$DEST/_headline/$(basename "$f")"
done

cat > "$DEST/README.md" <<'EOF'
# Presentation figures

One-stop folder for talk slides. Regenerated by:

```bash
python code/09_agent_figures.py --behavior outputs/agents/behavior_v3 \
  --stats outputs/agents/stats --out outputs/agents/figures
bash code/pack_presentation_figures.sh
```

## Layout

| folder | contents |
|---|---|
| `_headline/` | Short list of the main slides |
| `agents/` | Closed/agent v3 figures + **`agent_scale_all.png`** (open+closed) |
| `open_pipeline/` | Open-weight pipeline plots from `outputs/figures/` |
| `master_ladders/` | Talk-safe masters from `figures_final/` (no STALE closed ladders) |
| `mechanistic/` | Probe / RSA / dissociation extras |
| `w3_w4_w7/` | Steering, curriculum, Bruneau appendix |
| `extras/` | Mentor-packet uniques |

**Do not use** anything under `outputs/figures_final/_pending_rescore/` (contaminated closed rows).

## Naming / colors (agents)

- GPT-* = green (`#10a37f`)
- Gemini-* = blue (`#4285f4`)
- `agent_scale.png` = closed/agent roster only
- `agent_scale_all.png` = every model with behavioral `item_means`
EOF

n=$(find "$DEST" -name '*.png' | wc -l)
echo "Done: $n PNGs in $DEST"
